### ISSUE TITLE
Write detailed description of the system

### ISSUE THREAD

**Issue by danielchabr** [Damell/Korean-dining-advisor#1]

**Comment by torbentee** [comment]
## Technologies description:

Amazon Web Service free 12 month trial region east asia (Tokyo)

Java EE Framwork
- spring vs. ejb
  Object/Relational Mapping framework:
- hibernate
  DBMS: postgresql
- because hibernate is faster with it than mysql
  - (http://www.jpab.org/Hibernate.html)

glassfish (docker) vs tomcat
- maybe glassfish is oversized
- https://www.wikivs.com/wiki/GlassFish_vs_Tomcat?
- http://stackoverflow.com/questions/17239035/spring-and-tomcat-or-spring-and-glassfish

Versioncontrol:
- git – public repository at githaub
  - https://github.com/Damell/Korean-dining-advisor
- Testframework:
  - unit-test
  - Spring testing framework
    - http://docs.spring.io/spring/docs/current/spring-framework-reference/html/integration-testing.html
      Build tool:
  - maven vs gradle
    - https://spring.io/guides/gs/sts/

Why annotation and not xml?

**Comment by danielchabr** [comment]
https://jenkins-ci.org/
Log4j

**Comment by danielchabr** [comment]
Requirements

**Comment by danielchabr** [comment]
search
typeahead
browse
detail view
rating (thumbs up/thumbs down)
insert meal
edit

**Comment by danielchabr** [comment]
auth method

**Comment by torbentee** [comment]
# Detailed description of the system

## Requirements

The end user of our service should be able to have access to the system with a client. At first it is only planned to build a native application for the operating system Android. The system will offer an API which gives access to all of the features. Some feature will only be available for registered users.

### All users

All users should be able to get a list of all meals that are already recorded. It should also be possible to get detailed information of a specific meal. That contains the name of the meal in Hangul and English and a description. An image, the ingredients, a recipe and a rating shall be optional.
It should be possible to search for a name of a meal in Hangul or English. This search is planned to have a autocompletion.
A user should be able to sign up himself to the service. A user will have to enter a username, an e-mail address and a password to sign up to get more features. As an optional feature there should be a possibility to sign up with an OAuth account e.g. Facebook, Google+ or Twitter.

### Registered users

After the users are successfully signed up they should be able to sign in with their chosen username and password.
The registered user can do what an ordinary user can do and as well to change his own profile settings, add a meal or change an existing one.

## Features summary
- search for a meal in Hangul or English
  - autocompletion of the search
- get a list of all meals
- detail view of a meal
- rate a meal (thumbs up/thumbs down)
- insert a new meal
- edit a existing meal
- different authentication method (optional)
