### ISSUE TITLE
Technologies description

### ISSUE THREAD

**Issue by danielchabr** [Damell/Korean-dining-advisor#2]
Database, spring vs ejb, frontend, git, testing framework

**Comment by torbentee** [comment]
# What technologies we will use

## Java EE Framework

We decided to use the Spring Framework because we want to use Spring Boot to concentrate on coding. Additionally we need to configure just a few things. Another advantage of using Spring is that the developer can use POJOs (Plain Old Java Objects) to code. That means it is possible to program like one is used to it even if you’re not familiar with Java Enterprise developing.

## Object/Relational Mapping (ORM) framework

We expect to use Hibernate as an ORM framework. Spring can use Hibernate natively. Because of it. it will be easy to use a persistence layer for our data model. Furthermore there are some detailed examples of using Hibernate with Spring respectively Spring Boot on the internet.

## Version control

On the very popular hosting site github.com we will host our repository to collaborate our source code. Like the domain name say it uses Git as version control system.

## Build automation tool

As an tool to automate the build process of our distributed system we like to use Gradle. It combines the concepts of Apache Ant and Apache Maven. But it uses a more human readable language instead of XML.

## Logging Framework

To know what is going on with our distributed system we probably use the built in logging tool of the Spring Framework. It is also possible to change it for example to the log4j2 framework.

## Testing framework

In this project we want to use JUnit and/or Spring Testing Annotions to automate testing classes, methods and the integration.

## Continuous Integration

To automate the integration into our server system our team shall use a Jenkins server. Most of the testing and building will be done by this service for us.
