### ISSUE TITLE
APIs used

### ISSUE THREAD

**Issue by danielchabr** [Damell/Korean-dining-advisor#3]
dictionary API
images API
search API

**Comment by wook-jae** [comment]
Our application need to dictionary, search and image API. First we find wanted Korean dish through a search API. Dictionary API translate Korean menu into English or wanted language and they show us translated menu name. And we can look at menu image through image API. Finally we can easily order dinner.  

In order to find suitable image API, we consider google, naver, microsoft and daum open API. We select the most famous naver open image API in Korea because this application used in Korea. And naver open image API has a many merit. And we select the bing transte API because nevaer dictionary API service has terminated and google translate API is not free. And in order to provide transcription function, we use Glosbe API that convert text from one script to another

Naver open API feature 
- naver search API has 25,000 query/day processing limit
- naver open API is simple and easy to understand.
1. Image API
   - request URL : http://openapi.naver.com/search
- request parameter

![12](https://cloud.githubusercontent.com/assets/14276869/10544947/20e302a6-7461-11e5-877b-02882d2d4bf3.PNG)
- response field

![13](https://cloud.githubusercontent.com/assets/14276869/10544969/437fedba-7461-11e5-8cfb-0a5654d84f4e.PNG)

2 . Microsoft bing translate API

 Translate API Features
- bing translate API is free 2M-character/month
- dynamically access language.
- Because see sample code and libraries for ten different programming language, Translate API can easily be accessible
- provide transcription 

request URL : http://api.microsoftranslator.com/v2/Http.svc/Translaste
- request Parameters

![22](https://cloud.githubusercontent.com/assets/14276869/10545003/6265bd36-7461-11e5-9ba5-8b135f90ffa6.PNG)
- response field
  
  return value - A string representing the translated text.

3 . Glosbe API
 Overview 
- Glosbe offers programmatic access to dictionary translations and to translation memories as well
- Glosbe API is free to use
- request URL : https://glosbe.com/transliteration/api 
- request Parameters

![2](https://cloud.githubusercontent.com/assets/14276869/10581041/9ddd9396-76bb-11e5-9017-36c642f6bce4.PNG)
- response field
  
  Return value - A string representing the transliterate text.

**Comment by danielchabr** [comment]
Please add the transcription API
